import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import AmplitudeProvider from "@/components/AmplitudeProvider";

const pretendard = localFont({
  // 이때 node_modules는 해당 파일 위치의 상대경로로 한다.
  src: "../../public/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

// Raleway 폰트 설정
const raleway = Raleway({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "소금 | 소중한 나의 금",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/Favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${pretendard.className} ${raleway.variable} ${pretendard.variable} antialiased`}>
        <AmplitudeProvider>{children}</AmplitudeProvider>
      </body>
    </html>
  );
}
